---
functional:
- Пользователь должен иметь возможность искать товары по ключевому слову или категории.
- Пользователь должен иметь возможность фильтровать товары
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
- Пользователь может просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом.
- Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге.
- На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты.
non-functional:
- Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя.
- Сайт должен иметь мобильную версию.
- Сайт должен быть протестирован на совместимость с последними версиями браузеров.
- Сайт должен быть способен обрабатывать большое количество трафика
- Сайт должен быть доступен на различных устройствах
- На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без.
- Корзина хранится в сессии браузера.
implicit:
- Пользователь должен иметь возможность добавить товар в корзину и продолжить выбирать товары в каталоге
- Пользователь должен иметь возможность прелистывать старицы каталога товаров
- В каталоге и на странице товара должны выводиться название, рейтинг, цена со скидкой и без
- Сайт должен соответствовать законодательным актам
- Пользователь должен иметь возможность удалять товары из корзины
- Пользователь должен иметь возможность оформлять заказ
