---
functional:
- Пользователь должен иметь возможность искать товары по ключевому слову или категории.
- Пользователь должен иметь возможность фильтровать товары
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
- Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя.
- Сайт должен иметь мобильную версию.
- Сайт должен быть протестирован на совместимость с последними версиями браузеров.
- Сайт должен быть способен обрабатывать большое количество трафика
- Сайт должен быть доступен на различных устройствах
implicit:
- Пользователь должен иметь возможность зарегистрироваться
- Пользователь должен иметь возможность войти под своей учеткой
- У пользователя должна быть возможность заказа товара 
- Сайт должен отображаться корректно на разных языках 
- Пользователю должна быть доступна функция удаления товара из корзины 
- Пользователю должна быть доступна функция выбора языка
